INSERT INTO department (name) 
VALUES  ('Grocery'),
        ('Dairy'),
        ('Produce'),
        ('Drivers'),
        ('Online'),
        ('Shoppers'),
        ('Management');

INSERT INTO role (title, salary, department_id)
VALUES  ('Nightfill', 45, 1),
        ('Nightfill Captain', 50, 1),
        ('Dairy Fill', 45, 2),
        ('Dairy Captain', 50, 2),
        ('Produce Fill', 45, 3),
        ('Produce Captain', 50, 3),
        ('Delivery Driver', 55, 4),
        ('Lead Delivery Driver', 65, 4),  
        ('Shopper', 50, 5),
        ('Grocery Manager', 78, 6),
        ('Dairy Manager', 80, 6),
        ('Produce Manager', 80, 6),
        ('Online manager', 85, 6),
        ('Store Manager', 120, 6);


INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES  ('Lleyton', 'Hewitt', 14, NULL),
        ('Kevin', 'Magnussen', 13, 1),
        ('Jennifer', 'Aniston', 12, 1),
        ('Kim', 'Possible', 11, 1),
        ('Ronald', 'Weasley', 10, 1),
        ('Angelina', 'Jolie', 9, 2),
        ('Brad', 'Pitt', 9, 2),
        ('Barack', 'Obama', 9, 2),
        ('Benjamin', 'Franklin', 9, 2),
        ('Leonardo', 'Da Vinci', 9, 2),
        ('Michael', 'Bay', 8, 9),
        ('Jason', 'Statham', 7, 9),
        ('Tony', 'Parker', 7, 3),
        ('Blake', 'Griffen', 7, 13),
        ('Michael', 'Jordan', 6, 13),
        ('Lionel', 'Ritchie', 5, 13),
        ('Jordan', 'Dawson', 5, 13),
        ('Katie', 'Mater', 4, 4),
        ('Bill', 'Henderson', 3, 18),
        ('Greg', 'Davies', 3, 18),
        ('Sanam', 'Grace', 3, 18),
        ('Gretchin', 'Blake', 3, 18),
        ('Alan', 'Midas', 2, 5),
        ('Sarah', 'Young', 1, 23),
        ('Kevin', 'Jones', 1, 23),
        ('Aaron', 'Bates', 1, 23),
        ('Tony', 'Zhou', 1, 23);
    